language: python
python:
 - "3.7.4"
install:
 - pip install -e .
 - pip install pytest-cov codecov # Packages for Code Coverage
script:
 - pytest --cov=packages tests
after_success:
 - codecov # Report on codecov.io
